### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by kostuskest** [kulpin74/zabbix-ssl#12]
необходима более подробная инструкция по добавлению в мониторинг проверки доменных имен и наличия сертификатов
(с картинками результатов)

more detailed instructions for adding domain name verification and certificate availability to monitoring are needed

и хотелось бы увидеть шаблон на версию 5.0lts (если какая то помощь необходима то kostus-x@bk.ru)

**Comment by kostuskest** [comment]
\#проверяем какая версия ОС в зависимости от версии у нас будет применена инструкция
rpm --query centos-release

\#останавливаем сервер заббикса 
systemctl stop zabbix-server
#делаем резервные копии базы данных (использую логин и пароль заббикса) 
/usr/bin/mysqldump --opt -v --databases zabbix -uzabbix -p'password' | /usr/bin/gzip -c > /root/zabbix.sql.gz cp -R /usr/share/zabbix /root 
#добавляем репозиторий для обновления нашей ОС 
rpm -Uvh https://repo.zabbix.com/zabbix/4.4/rhel/8/x86_64/zabbix-release-4.4-1.el8.noarch.rpm

\#очищаем и пересоздаем кэш пакетного установщика 
yum clean all 
yum makecache

\#проверяем какие пакеты заббикса установлены 
rpm -qa | grep zabbix

# обновляем пакеты zabbix т.к. в моем случае zabbix_appliance (отдельная виртуальная машина с заббиксом то я делаю обновляю полностью все пакеты

\#yum upgrade zabbix-server-mysql zabbix-web zabbix-agent zabbix-get zabbix-sender yum update

\#Устанавливаем русский язык 
dnf install glibc-langpack-ru -y

\#после перезагрузки не открывается заббикс (необходимо скопировать конфиг из share в httpd) и скопировать файлы из /usr/share/zabbix в каталог /var/www/html/

vi /etc/httpd/conf.d/zabbix.conf 
cp -r /usr/share/zabbix/ /var/www/html

\#перезапускаем сервис httpd 
systemctl restart httpd

\#проверяем доступность нашей системы мониторина http://Ipaddress/zabbix (login:Admin password:zabbix)

\#устанавливаем пакеты whois bc нужны для работы скриптов в шаблоне yum install whois bc -y

\#Копируем файлы шаблона в /usr/lib/zabbix/externalscripts/

scp -r /home/{$USER}/Downloads/zabbix-ssl-master/externalscripts/\* root@192.168.1.14(адрес нашего хоста с заббиксом):/usr/lib/zabbix/externalscripts/

\#включаем разрешение исполнения внешних обработок в конфигурации zabbix_agentd.conf

vi /etc/zabbix/zabbix_agentd.conf

\#находим там строчку # EnableRemoteCommands=0 и меняем

EnableRemoteCommands=1

\#доабвляем xml шаблона в заббикс

\#привязываем шаблон к узлу "zabbix server"

**Comment by kulpin74** [comment]
Инструкцию по установке zabbix нужно смотреть на https://www.zabbix.com/documentation/current/manual/installation. Там по всем ОС и по всем вариантам установки и это точно более верно.

Установка шаблона в систему стандартна, если вы готовы подготовить инструкцию с шагами и картинками, то сделайте PR.

Выкладывать отдельный шаблон для 5 версии смысла особого не вижу, 5 версия спокойно загрузит шаблон, каких-то новых фич 5 версии шаблон не использует.

**Comment by kostuskest** [comment]
ну да, это предварительная версия инструкции, в ней все указано чего не хватало для полноценного функционирования вашего шаблона, картинки будут, но чуть позже, я для этого в этой задаче все и размещаю, чтобы помочь вам привести шаблон к использованию даже если человек "не понимает, но оочень надо"

**Comment by kulpin74** [comment]
ок, если подготовите инструкцию - то как говорится welcome, но я не хочу размещать у себя инструкций по установке zabbix, можно ссылку на офф документацию дать.

Ну и все же я рассчитываю на то что шаблон для пользователей которые понимают что такое шаблоны, как ими пользоваться и для чего они.
По всем вопросам непонимания - есть ишью, я там отвечу обязательно, если совсем все плохо - тогда надо сначала надо изучить как вообще работает zabbix.
