### ISSUE TITLE
Whois com.ua

### ISSUE THREAD

**Issue by Satrier** [kulpin74/zabbix-ssl#13]
Скрипт whois_expire.sh  некорректно работает с доменами com.ua
к примеру expires:          2022-02-10 19:07:59+02
обрезает как 19:07:59+02

**Comment by kulpin74** [comment]
Мда, все регистраторы возвращают время в ISO формате,  а тут "T" между датой и временем пропущено :(((( Посмотрю что можно сделать

**Comment by Satrier** [comment]
А если так?
`whois yandex.com.ua 2>&1 | grep -Ei 'expires|Expiration|Expires on|Expiry date|paid-till|expires' | grep -o -E '[0-9]{4}.[0-9]{2}.[0-9]{2}|[0-9]{2}/[0-9]{2}/[0-9]{4}' | awk 'NR == 1'`

**Comment by Satrier** [comment]
@kulpin74 это решено, новая проблема с дискавери
