### ISSUE TITLE
Domain discovery com.ua

### ISSUE THREAD

**Issue by Satrier** [kulpin74/zabbix-ssl#14]
![image](https://user-images.githubusercontent.com/10636815/107142148-8b871100-6935-11eb-95e3-5d543711ec67.png)
Вместо полного домена добавляется  #com.ua
whois_expire.sh[com.ua]
--

**Comment by kulpin74** [comment]
Ну в целом даже не знаю. Смотрите, я исходил из того что в файлике кучка хостов, которые нужно проверять на корректность SSL сертификатов, ну и потом была прикручена проверка просроченности доменных имен. Но я исходил что это доменные имена верхнего уровня, потому что во-первых не вижу возможности выяснить в общем случае какого уровня доменное имя, во вторых в большинстве своем они все же именно такие.
Для того что бы добиться мониторинга в вашей ситуации вижу два варианта:
1. Сделать два файла, один с хостами, второй с доменами.
2. Сделать указание в файле на уровень доменного имени, которые нужно проверять.

**Comment by Satrier** [comment]
переделал всё на URL

**Comment by Satrier** [comment]
![image](https://user-images.githubusercontent.com/10636815/107278376-63470180-6a5e-11eb-98f5-408038d42550.png)

**Comment by kulpin74** [comment]
Ну да, если основная цель мониторинг доменных имен - то норм
