### ISSUE TITLE
Несработка для нового хоста с уже просроченным сертификатом

### ISSUE THREAD

**Issue by braintweak** [kulpin74/zabbix-ssl#17]
Спасибо, самый простой для настройки скрипт из тех, что попробовал на заббиксе.
Но обратил внимание, что почему-то не отрабатывает проверка автоматически добавленного хоста, у которого уже просрочен сертификат. 
В Latest data написано: 
Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "-1"
Я что-то неверно сделал в настройке или все-таки в шаблоне ошибка?

**Comment by kulpin74** [comment]
Пожалуй это ошибка шаблона, в целое положительно число -1 никак не получится затолкать, подумаю как лучше порешать

**Comment by kulpin74** [comment]
Да, проще всего поменять тип информации для прототипа `SSL certificate validity {#URL}:{#PORT}` c `числовой (целое положительное)` на `числовой (с плавающей точкой)`. Кажется этого должно быть достаточно. Позже проеверю и закачу новую версию файла шаблона

**Comment by braintweak** [comment]
Да, поменять тип - помогло. Только пришлось удалить все уже созданные правила, т.к. они не перезаписываются автоматом.
