### ISSUE TITLE
Possible to update items from url instead of local file?

### ISSUE THREAD

**Issue by remote24** [kulpin74/zabbix-ssl#19]
Would it be possible to adapt this in some way to use a web URL serving the json data instead of the ssl_check.json file in externalscripts-folder.

**Comment by kulpin74** [comment]
I think it's possible. Will add new disabled discovery on next week.

**Comment by kulpin74** [comment]
@remote24 Is it possible to see the changes in the templates? PR: #20.

**Comment by remote24** [comment]
Yes it works great! Thanks for the updated template.
